### ISSUE TITLE
Schätzung für User Stories

### ISSUE THREAD

**Issue by kschaedler** [FHWestkuesteSWE/projektgebaeude-team-3#1]
Achtung bei Ihren Schätzungen: Eine fertige Story bedeutet mindestens: Entwurf gemacht und dokumentiert, Story programmiert und umfassend ausgetestet. Das schaffen Sie auch für kleine Stories kaum in einer Stunde.

**Comment by KaUm25** [comment]
Schätzungen sind angepasst
